/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditTaskView.java
 *
 * Created on 15 nov. 2011, 13:03:40
 */
package PlanningViews;

import Planning.DateUtils;
import Planning.PlanningApp;
import PlanningData.LinkWithDB;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JCheckBox;
import javax.swing.JFrame;

/**
 *
 * @author Audrey
 */
public class EditTaskView extends javax.swing.JFrame {

    private LinkWithDB DB;
    private Date currentDay;
    private JFrame taskView;
    private TaskPanel taskPanel;
    
    public EditTaskView(TaskFrame view, String currentDay, String message) {
        // TODO : Crée un editTaskView avec des éléments déjà connus
    }
    
    
    /** Creates new form EditTaskView */
    public EditTaskView(TaskFrame view, Date currentDay) {     
        initComponents();
        
        this.taskView = view;
        taskPanel = view.getPanel();
        
        this.setLocationRelativeTo(view);
        dateBeginLabel.setText(DateUtils.dateToString(currentDay));
        dateEndLabel.setText(dateBeginLabel.getText());    
        this.currentDay = currentDay;
        this.DB = PlanningApp.getApplication().getLinkWithDB();
        
        setVisible(true);
        view.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupOcc = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionArea = new javax.swing.JTextArea();
        allDayBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        checkBoxOcc = new javax.swing.JCheckBox();
        dailyOcc = new javax.swing.JRadioButton();
        monthlyOcc = new javax.swing.JRadioButton();
        yearlyOcc = new javax.swing.JRadioButton();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        dateBeginLabel = new javax.swing.JLabel();
        dateEndLabel = new javax.swing.JLabel();
        weeklyOcc = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hoursBeginBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        minutesBeginBox = new javax.swing.JComboBox();
        hoursEndBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        minutesEndBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(Planning.PlanningApp.class).getContext().getResourceMap(EditTaskView.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setName("jPanel1"); // NOI18N

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setFocusable(false);
        jLabel1.setName("jLabel1"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        descriptionArea.setColumns(20);
        descriptionArea.setRows(5);
        descriptionArea.setName("descriptionArea"); // NOI18N
        jScrollPane1.setViewportView(descriptionArea);

        allDayBox.setText(resourceMap.getString("allDayBox.text")); // NOI18N
        allDayBox.setFocusPainted(false);
        allDayBox.setFocusable(false);
        allDayBox.setName("allDayBox"); // NOI18N
        allDayBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allDayBoxActionPerformed(evt);
            }
        });

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setFocusable(false);
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setFocusable(false);
        jLabel3.setName("jLabel3"); // NOI18N

        checkBoxOcc.setText(resourceMap.getString("checkBoxOcc.text")); // NOI18N
        checkBoxOcc.setFocusPainted(false);
        checkBoxOcc.setFocusable(false);
        checkBoxOcc.setName("checkBoxOcc"); // NOI18N
        checkBoxOcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxOccActionPerformed(evt);
            }
        });

        buttonGroupOcc.add(dailyOcc);
        dailyOcc.setText(resourceMap.getString("dailyOcc.text")); // NOI18N
        dailyOcc.setEnabled(false);
        dailyOcc.setFocusable(false);
        dailyOcc.setName("dailyOcc"); // NOI18N

        buttonGroupOcc.add(monthlyOcc);
        monthlyOcc.setText(resourceMap.getString("monthlyOcc.text")); // NOI18N
        monthlyOcc.setEnabled(false);
        monthlyOcc.setFocusable(false);
        monthlyOcc.setName("monthlyOcc"); // NOI18N

        buttonGroupOcc.add(yearlyOcc);
        yearlyOcc.setText(resourceMap.getString("yearlyOcc.text")); // NOI18N
        yearlyOcc.setEnabled(false);
        yearlyOcc.setFocusable(false);
        yearlyOcc.setName("yearlyOcc"); // NOI18N

        saveButton.setText(resourceMap.getString("saveButton.text")); // NOI18N
        saveButton.setMaximumSize(new java.awt.Dimension(72, 23));
        saveButton.setMinimumSize(new java.awt.Dimension(72, 23));
        saveButton.setName("saveButton"); // NOI18N
        saveButton.setPreferredSize(new java.awt.Dimension(72, 23));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(resourceMap.getString("cancelButton.text")); // NOI18N
        cancelButton.setMaximumSize(new java.awt.Dimension(72, 23));
        cancelButton.setMinimumSize(new java.awt.Dimension(72, 23));
        cancelButton.setName("cancelButton"); // NOI18N
        cancelButton.setPreferredSize(new java.awt.Dimension(72, 23));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        dateBeginLabel.setText(resourceMap.getString("dateBeginLabel.text")); // NOI18N
        dateBeginLabel.setName("dateBeginLabel"); // NOI18N

        dateEndLabel.setText(resourceMap.getString("dateEndLabel.text")); // NOI18N
        dateEndLabel.setName("dateEndLabel"); // NOI18N

        buttonGroupOcc.add(weeklyOcc);
        weeklyOcc.setText(resourceMap.getString("weeklyOcc.text")); // NOI18N
        weeklyOcc.setEnabled(false);
        weeklyOcc.setFocusable(false);
        weeklyOcc.setName("weeklyOcc"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        hoursBeginBox.setModel(new javax.swing.DefaultComboBoxModel(DateUtils.getHours()));
        hoursBeginBox.setName("hoursBeginBox"); // NOI18N
        hoursBeginBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoursBeginBoxActionPerformed(evt);
            }
        });

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        minutesBeginBox.setName("minutesBeginBox"); // NOI18N
        String[] list = new String[60];
        for(int i=0 ; i<60 ; i++) {
            if(i<10)
            list[i] = "0"+i;
            else list[i] = i+"";
        }
        minutesBeginBox.setModel(new DefaultComboBoxModel(DateUtils.getMinutes()));
        minutesBeginBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minutesBeginBoxActionPerformed(evt);
            }
        });

        hoursEndBox.setModel(new javax.swing.DefaultComboBoxModel(DateUtils.getHours()));
        hoursEndBox.setName("hoursEndBox"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        minutesEndBox.setModel(new javax.swing.DefaultComboBoxModel(DateUtils.getMinutes()));
        minutesEndBox.setName("minutesEndBox"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(checkBoxOcc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(allDayBox, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateBeginLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateEndLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(hoursEndBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minutesEndBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(hoursBeginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(minutesBeginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dailyOcc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(weeklyOcc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(monthlyOcc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yearlyOcc)
                                .addGap(54, 54, 54)))
                        .addGap(83, 83, 83)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                .addGap(111, 111, 111))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(allDayBox)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dateBeginLabel)
                    .addComponent(jLabel4)
                    .addComponent(hoursBeginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(minutesBeginBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(dateEndLabel)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(checkBoxOcc))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hoursEndBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(minutesEndBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dailyOcc)
                    .addComponent(weeklyOcc)
                    .addComponent(monthlyOcc)
                    .addComponent(yearlyOcc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkBoxOccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxOccActionPerformed
        if(evt.getSource() instanceof JCheckBox) {
            JCheckBox check = (JCheckBox)evt.getSource();
            if(check.isSelected()) {
                dailyOcc.setEnabled(true);
                weeklyOcc.setEnabled(true);
                monthlyOcc.setEnabled(true);
                yearlyOcc.setEnabled(true);
            }
            else {
                dailyOcc.setEnabled(false);
                weeklyOcc.setEnabled(false);
                monthlyOcc.setEnabled(false);
                yearlyOcc.setEnabled(false);
            }
        }
    }//GEN-LAST:event_checkBoxOccActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(allDayBox.isSelected())
            DB.addValue(DateUtils.dateToString(currentDay),descriptionArea.getText(),getRecurrence());
        else {
            // TODO : modifier Time
//            Time begin = new Time(new Long(((String)hoursBeginBox.getSelectedItem()+minutesBeginBox.getSelectedItem()+"00")));
//            System.out.println("Time begin: "+begin);
//            System.out.println((String)hoursBeginBox.getSelectedItem());
//            Time end = new Time(new Long(((String)hoursEndBox.getSelectedItem()+minutesEndBox.getSelectedItem()+"00")));
//            System.out.println("Time end: "+end);
            String timeBegin = ((String)hoursBeginBox.getSelectedItem()+":"+minutesBeginBox.getSelectedItem());
            String timeEnd = ((String)hoursEndBox.getSelectedItem()+":"+minutesEndBox.getSelectedItem());
            DB.addValue(DateUtils.dateToString(currentDay),timeBegin,timeEnd,descriptionArea.getText(),getRecurrence());
        }
        PlanningApp.getApplication().getView().initDisplay();
        taskPanel.displayDatasOfDay();
        taskView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        taskView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void allDayBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allDayBoxActionPerformed
        if(allDayBox.isSelected()) {
            dateEndLabel.setText(dateBeginLabel.getText());
//            hoursBeginBox.setSelectedItem((String)"00");
//            minutesBeginBox.setSelectedItem((String)"00");
//            hoursEndBox.setSelectedItem((String)"23");
//            minutesEndBox.setSelectedItem((String)"59");
            
            hoursBeginBox.setEnabled(false);
            minutesBeginBox.setEnabled(false);
            hoursEndBox.setEnabled(false);
            minutesEndBox.setEnabled(false);
        }
        else {
            hoursBeginBox.setEnabled(true);
            minutesBeginBox.setEnabled(true);
            hoursEndBox.setEnabled(true);
            minutesEndBox.setEnabled(true); 
        }
    }//GEN-LAST:event_allDayBoxActionPerformed

    private void hoursBeginBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoursBeginBoxActionPerformed
        // The ending hour is the same than the beginning hour //
        hoursEndBox.setSelectedItem(hoursBeginBox.getSelectedItem());
    }//GEN-LAST:event_hoursBeginBoxActionPerformed

    private void minutesBeginBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minutesBeginBoxActionPerformed
        minutesEndBox.setSelectedItem(minutesBeginBox.getSelectedItem());
    }//GEN-LAST:event_minutesBeginBoxActionPerformed

    /**
     * Return the string for the recurrence selected or NONE
     * @return String
     */
    private String getRecurrence() {
        if(checkBoxOcc.isSelected()) {
            if(dailyOcc.isSelected())
                return "DAY";
            else if(weeklyOcc.isSelected())
                return "WEEK";
            else if(monthlyOcc.isSelected())
                return "MONTH";
            else return "YEAR";
        }
        else return "NONE";
    }
    
    public void setDatasToEdit(int idTask) {
        ResultSet rs = PlanningApp.getApplication().getLinkWithDB().getTask(idTask);  
        if(rs==null)    return;
        
        try {
            while(rs.next()){
                descriptionArea.setText(rs.getString("description"));
                long begin = rs.getTime("time_beginning").getTime();
                Date d = new Date();
                d.setTime(begin);
                long end = rs.getTime("time_end").getTime();
                d.setTime(end);
            }
        } catch(SQLException e) {
            System.err.println(e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTaskView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTaskView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTaskView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTaskView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//
//            public void run() {
//                new EditTaskView().setVisible(true);
//            }
//        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox allDayBox;
    private javax.swing.ButtonGroup buttonGroupOcc;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox checkBoxOcc;
    private javax.swing.JRadioButton dailyOcc;
    private javax.swing.JLabel dateBeginLabel;
    private javax.swing.JLabel dateEndLabel;
    private javax.swing.JTextArea descriptionArea;
    private javax.swing.JComboBox hoursBeginBox;
    private javax.swing.JComboBox hoursEndBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox minutesBeginBox;
    private javax.swing.JComboBox minutesEndBox;
    private javax.swing.JRadioButton monthlyOcc;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton weeklyOcc;
    private javax.swing.JRadioButton yearlyOcc;
    // End of variables declaration//GEN-END:variables
}
